### ISSUE TITLE
AltDrag sticky window snapping leaves empty space in-between windows.

### ISSUE THREAD

**Issue by loligans** [stefansundin/altdrag#101]
AltDrag is running as administrator.
**Monitor:** BenQ 32-inch Monitor
**GPU:** NVidia GTX 1070Ti
**GPU Interface:** Thunderbolt 3 Sonnet Breakaway Box
**Windows Version:** 1803 (OS Build 17134.523)
**Monitor Resolution:** 4k (3840x2160)
**Display Scaling:** 150%
DPI Scaling set to Application.
![image](https://user-images.githubusercontent.com/3218210/52529199-be449300-2ca2-11e9-887c-1ab8e97f20eb.png)

**Problem:**
When dragging windows, AltDrag will snap to what appears to be invisible window borders. Here is a screenshot showing the space in-between windows after a window snap operation. I have surrounded the space in-between the windows with red boxes to help illustrate my point.
![image](https://user-images.githubusercontent.com/3218210/52529237-65c1c580-2ca3-11e9-9435-7c54bf92a04c.png)
One thing to point out is when the Taskbar is oriented at the top of the screen, AltDrag will snap correctly to the Taskbar. However, when I orient the Taskbar to the bottom of the screen, AltDrag will exhibit the same behavior of space in-between the windows. Windows will still align correctly at the top of the screen. Here is a screenshot of what I mean.
![image](https://user-images.githubusercontent.com/3218210/52529312-69a21780-2ca4-11e9-9606-afb7ae172c89.png)

**Expectation:**
Windows should snap directly to their borders without extra space in-between. I could see a feature coming out of this by specifying a number of units of padding in-between windows when snapping.

**Comment by loligans** [comment]
Setting display scaling to 100% does not fix this issue.
Turning off DPI Scaling override does not fix this issue
Setting display resolution to 1920x1080 does not fix this issue.

**Comment by celynwalters** [comment]
Probably the same issue as #38 (opened back in 2015, may do a PR with my fix when I get a chance)

**Comment by loligans** [comment]
You're right. I'll close this in favor of issue #38
