### ISSUE TITLE
Put the focus to the dragging window 

### ISSUE THREAD

**Issue by mmahmoudian** [stefansundin/altdrag#121]
## The issue
When a window is off focus and you start dragging it, it stays on focus and it gets lost behind other windows. The most annoying moment is when you move an off-focus window from another monitor to the monitor that you have a maximized focused window in.

## Solution
right before dragging the window, put it in focus first.

## Customization
I can see that some users might want to keep the current behavior, therefore, it can be added as an option that is on by default (because imho it makes sense as you are clicking the window to start dragging and naturally clicking a window should bring it to focus).

**Comment by Drarig29** [comment]
There is this feature already, have a look in the configuration window:

![image](https://user-images.githubusercontent.com/9317502/90230673-2fc24c00-de1a-11ea-8ea1-8e8f16a8e41c.png)

**Comment by mmahmoudian** [comment]
Thanks. It is such an obvious feature that I thought it should be on by default and it never occurred to me that it can be something to be turned on in the settings.
