### ISSUE TITLE
Top of monitor maximizes/resizes even if aero snap mimicing is disabled?

### ISSUE THREAD

**Issue by jnatten** [stefansundin/altdrag#131]
Is this behaviour intended?
I have monitors on top of my main one and moving windows between them is a pain when dragging to the top of the lower one maximizes the window.

Is there a way (or planned way) to disable maximizing on top?

**Comment by RamonUnch** [comment]
When aero-snap  is disabled windows should not maximize on top, and should not snap on the sides.
However be sure that the Aero=0 in the [General] section of AltDrag.ini in altdrag's directory and restart altdrag.
Maybe you are running AltDrag from program files directory and in this case AltDrag have have no right to modify the ini file.

**Comment by jnatten** [comment]
Aero-snap was already disabled, but it was scaling that was messing me up (My top monitors were 150%).
After reading the known issues section in the docs i tried disabling scaling which fixed the issue.

The workaround mentioned in [this comment](https://github.com/stefansundin/altdrag/issues/7#issuecomment-314945425) fixed the issue with scaling enabled.

Thanks for the help!

**Comment by RamonUnch** [comment]
@jnatten 
I am also keeping updated a [fork of AltDrag ](https://github.com/RamonUnch/AltDrag/releases)that fixes most of those bugs. And importantly some freezing bugs. You may be interested.
