### ISSUE TITLE
AltDrag Virus.W32.ETap detection on VirusTotal

### ISSUE THREAD

**Issue by Kr1sL** [stefansundin/altdrag#144]
Looks like SecureAge APEX marked AltDrag as a match for the W32.ETap virus on virustotal.
[Detection Link](https://www.virustotal.com/gui/file/68f145aed758a51b638632c4b3fb61343827a72a7f96ef8f4fba64c117451a02/detection)

**Comment by garoto** [comment]
Who gives a shit about snake oil AV shenanigans? Only people with nothing better to do and with a github account, that's who.

**Comment by Kr1sL** [comment]
lol! Since we're here, is it actually snake oil? I figured it was someone being a jerk / falsely claiming malicious activity. I'm really curious about that snake oil claim though.

**Comment by stefansundin** [comment]
This happens from time to time and unfortunately there's very little we can do to prevent it. I'm not really worried about it unless one of the big vendors have a false positive. And yes, funny comment about snake oil AV vendors 😀, it's actually not that far from the reality. In addition to bad heuristics, they also do not really have an easy way to report false positives. But if someone here is worried, please feel free to find a way to submit a false positive report and then submit it yourself (and then let us know here how you reported it, if we need to do it again in the future).

**Comment by Kr1sL** [comment]
Uploaded compressed .exe [here](https://www.secureage.com/article-report-false-positive) for review. The process is similar to getting removed from mail spam blacklists (which we all know is super great). Received the following ~24 hours later. Should be good soon.

"Hello,

Your submission (20211011-172312725500/AltDrag.zip) has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us at secureaplus@secureage.com if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result.

Thank you for your report.

SecureAPlus Admin"
