### ISSUE TITLE
Scroll is disabled in paste panel & emoji panel

### ISSUE THREAD

**Issue by adamp4** [stefansundin/altdrag#151]
Hi Stefan,
Thanks a lot for sharing a such good tool.
As mentioned in title, scoll is disabled in in paste panel & emoji panel even after adding the class name (Also in start menu, but it's been solved by adding class name "Windows.UI.Core.CoreWindow")
<img width="611" alt="image" src="https://user-images.githubusercontent.com/44283910/154796400-a3424542-a4ca-4beb-9351-4dfed6a4ac4c.png">
![image](https://user-images.githubusercontent.com/44283910/154796422-2338af7c-5c5b-4960-a04e-cda9c061f6c5.png)

**Comment by RamonUnch** [comment]
Be sure to disable the **Scroll Incative windows** option in the General tab, when you are using Windows 10,
Windows 10 by default scroll incative windows (can be configured in the system config).
Related issues: #147, #3, #83

**Comment by adamp4** [comment]
> Be sure to disable the **Scroll Incative windows** option in the General tab, when you are using Windows 10, Windows 10 by default scroll incative windows (can be configured in the system config). Related issues: #147, #3, #83

Very quick & helpful reply, didn't notice that before, thanks ^_^
