### ISSUE TITLE
Is X or D Input support possible? 

### ISSUE THREAD

**Issue by ariadesu** [stefansundin/altdrag#154]
Using a DInput key as hotkey for drag/resize. This would allow some mice and other peripherals (primarily gamepads) to be a little easier to configure.

**Comment by RamonUnch** [comment]
for now only keys that generate a virtual key keyboard event can be mapped for hotkey. My fork also allows mouse buttons to be mapped as hotkeys, but it is for sure possible to use a program to re-map gamepad buttons to keyboard, I would suggest you take a look at [AntiMicro](https://github.com/AntiMicro/antimicro)

**Comment by ariadesu** [comment]
I was hoping that by making it native D input, I'd reduce conflicts where the keyboard hotkey is taken by something else. My mouse doesn't allow mapping mouse buttons beyond M5, but it does allow X and Dinput (and keyboard) mapping. I was hoping to set a mouse button to drag and one to resize.

**Comment by RamonUnch** [comment]
If you want to use mouse Xbuttons to move/resize windows I sugget you try [my fork](https://github.com/RamonUnch/AltSnap/releases), Stefan is no longer active in the development.

**Comment by RamonUnch** [comment]
If your mouse allows for keyboard mapping then you simply need to map the button you want to a right win for example.
Also the latst versions of my fork has some bugs if you combine MB4/5 to hotclicks+move/resize, I will fix it soon.

**Comment by RamonUnch** [comment]
fix: https://github.com/RamonUnch/AltSnap/issues/172

**Comment by ariadesu** [comment]
Thank you. I've switched to your fork. I wanted to use M6 and M7 rather than 4 and 5, but for now I have a workable solution with keyboard emulation.

**Comment by RamonUnch** [comment]
I think the details on your setup would be interesting to people.

**Comment by ariadesu** [comment]
I'm using a Roccat Leadr, which doesn't allow mapping to F keys beyond 12, or to regional keys; instead it uses the ISO position of those keys. (These are among an extensive list of grievances). The Leadr has two buttons left of the left click. I use these for move and resize. These are not M4 and 5, as those are on the thumb rest. Though you can map any button to send M4 and M5, I didn't want to do that since I do use M4 and M5's functionality in the browser (though I have them mapped to the hat above the mouse wheel).
To avoid conflicts, I used the key remapper in PowerToys so I can use keys that aren't on ISO keyboards and therefore hopefully aren't listened for by anything other than AltSnap. Another possible solution is to launch an application which will type the obscure key combination for me, as launching arbitrary applications is supported by the mouse software. But this felt sluggish. Possibly my fault.

Because DInput allows 128 unique buttons, and can be made exclusively visible to only one application by the user, I thought it would be well suited for this. XInput doesn't have this flexibility, but it is the modern gamepad interface, so implementing DInput support in 2022 without acknowledging XInput would probably be odd. Further, XInput is the interface for the Microsoft Adaptive Controller, which is one of the most popular products for low tech custom inputs.

**Comment by RamonUnch** [comment]
I am actually working in extending AltSnap to 9 buttons, as long as the buttons have been mapped to a key. It could be a key outside of the keyboard (ie F13 through F24) or even maybe keys that are marked unmapped in  the MS doc. I will post an issue soon in my repo
