### ISSUE TITLE
Alt+Drag (probably falsley) detected as Malware on VirusTotal (2/75)

### ISSUE THREAD

**Issue by xcy7e** [stefansundin/altdrag#174]
Hi there,

on virustotal there is 2 matches out of 75 for alt+drag, claiming:
- W32.AIDetectMalware (by Bkav Pro)
- Virus.W32.ETap (by MaxSecure)

This caught my attention via Microsoft's Process Explorer.

Can one explain this to me?
I had this result on multiple systems, so I presume it's totaly legit.
Maybe it's worth digging into from the coding perspective to see if it can be avoided. At least for the sake of compliance.

VirusTotal match: https://www.virustotal.com/gui/file/68f145aed758a51b638632c4b3fb61343827a72a7f96ef8f4fba64c117451a02/detection

**Comment by RamonUnch** [comment]
#112
#144

basically those are generic algorithms that detect wrongly AltDrag as infected.
The reason is probably because it uses a low level mouse and keyboard hook, thus it looks like a keylogger to some AVs.
