### ISSUE TITLE
Windows 23H2v2 conflict with Alt + TAB task switcher

### ISSUE THREAD

**Issue by plaguewolf** [stefansundin/altdrag#177]
Previously I had no issues with using both altdrag and windows task switcher.
*|TaskSwitcherWnd
*|TaskSwitcherOverlayWnd
are both in my blacklist, but i cannot click on windows in the task switcher anymore and now can drag the task switcher overlay with altdrag. disabling altdrag allows me to interact with task switcher normally.

**Comment by RamonUnch** [comment]
maybe `*|Windows.UI.Core.CoreWindow` could do it?
or maybe `*|XamlExplorerHostIslandWindow`

In order to be sure you can try to use the Window Spy program from auto hotkey. and check with the *Follow mouse* option

EDIT look at #145

**Comment by plaguewolf** [comment]
The first one fixed it, thanks.
