### ISSUE TITLE
Installer UAC compliance

### ISSUE THREAD

**Issue by Link-Satonaka** [stefansundin/altdrag#24]
The installer does not properly comply with UAC- instead of requesting elevation during the install process, the entire installer is elevated. This results in two bugs/flaws:

1. If "Run AltDrag" is checked on the final page, AltDrag is run as the  administrative user, when it should be run as the regular user. In practice this will only result in the user losing their configuration when AltDrag closes (and it is next started as a completely different user), but it should be fixed nonetheless...

2. The installer deposits shortcuts in the Start Menu of the user that ran the installer- which is currently the administrator, which means AltDrag's shortcuts will not appear in the start menu of the user! You do not ask the user if they want to install for "just me" or "everybody". The reasonable default is for "everybody", so AltDrag's shortcut should be deposited here: `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`.

If you wanted to install for "just me"- an option which does not require elevation at all, altdrag would be installed to `%APPDATA%\AltDrag` and the shortcuts would be placed where you have them currently, `%APPDATA%\Microsoft\Windows\Start Menu`. But since you install to `Program Files` and incorrectly elevate the entire installer, my user folder is `C:\Users\Link` but the start menu shortcuts end up in `C:\Users\root\...\Start Menu` (where `root` is my administrative user).

Please fix! Thank you.

**Comment by stefansundin** [comment]
It was done like this because it is the easiest way to make NSIS elevate the installer.

1. The user will not lose their configuration, since it is not stored in a user-specific location. I agree it is not ideal to run the program elevated, but I'd rather do that than having users become frustrated the first time the app is run because they are trying to drag elevated programs.

2. Maybe you are right, maybe I should add it to all users instead. I haven't really thought about this because all my computers only have one user.

I built AltDrag when installing stuff in `Program Files` was more common. I agree that it is probably time to revise that and start installing in `%APPDATA%`.

Thank you for your input.

**Comment by Link-Satonaka** [comment]
I am perfectly fine with installing to `Program Files`, I only mentioned `%APPDATA%` as an option where the installer doesn't require elevation at all.

The default for `Elevate to administrator privileges` is off, so it seems MORE inconsistent to me that you would have an elevated AltDrag for just the first session ("why could I drag this window before now suddenly I can't?!")

It is possible to operate on administrative windows without running the process as an administrator. It works by installing a system certificate- I don't know the details, but you can look through the source code here:
http://www.autohotkey.com/board/topic/70449-enable-interaction-with-administrative-programs/
And this article is referenced in the above link
https://msdn.microsoft.com/en-us/library/bb756929.aspx

**Comment by stefansundin** [comment]
I have never seen the system certificate thing before, thanks!

**Comment by Link-Satonaka** [comment]
It might not be a viable solution since the formal process seems to involve a yearly payment for a signed cert, but if you are able to implement a self-signed cert for the more technically inclined users (as AHK did), that'd be more than fine too!

**Comment by Zer0t3ch** [comment]
> I built AltDrag when installing stuff in `Program Files` was more common. I agree that it is probably time to revise that and start installing in `%APPDATA%`.

This wouldn't really be practical when trying to install system-wide for all users.

**Comment by Nindaleth** [comment]
If installing for all users, `%ALLUSERSPROFILE%` can be used (or `%PROGRAMDATA%` for Windows Vista and newer).

**Comment by stefansundin** [comment]
I hope everyone is happy with the solution I picked: https://github.com/stefansundin/altdrag/commit/26798054b584bbca06c64106bc3113f124c00768

Let me know if you have opinions. :)

**Comment by Link-Satonaka** [comment]
This change probably requires an uninstall of the old version first, right?

I'll test it out when I next get the chance

**Comment by stefansundin** [comment]
Yup, I put this note on the upgrade page:

>  Note: version 1.1 and later defaults to install to the user directory. If you are upgrading from a previous version, then I recommend that you first uninstall and then install from scratch. Otherwise you have to right click the installer and use 'Run as administrator'.
