### ISSUE TITLE
Alt-tab is draggable on Windows 10

### ISSUE THREAD

**Issue by plttn** [stefansundin/altdrag#35]
I've tried to find the classname of alt-tab, but I can't grab the classname of it with either altdrag.exe or process monitor.

Side effect of this is you cannot click a window in alt-tab anymore.

**Comment by Zer0t3ch** [comment]
Ditto. It seems that `*|TaskSwitcherWnd` is already in the stock blacklist, but it must have been changed in Win10.

**Comment by stefansundin** [comment]
Try blacklisting `*|MultitaskingViewFrame`.

**Comment by stefansundin** [comment]
Also, the blacklist rule for the volume window in Windows 10 is `*|Windows.UI.Core.CoreWindow`. The old rule for this was `|#32770`.

This shouldn't be needed unless you have _Scroll inactive windows_ enabled, which is a little pointless if you are running on Win 10.

**Comment by trustin** [comment]
Regardless whether 'Scroll inactive windows' is enabled, I can drag the alt-tab window.

**Comment by stefansundin** [comment]
Excellent. I will add these windows to the default blacklist in the next version. Thanks!

**Comment by trustin** [comment]
Thank you, @stefansundin :-)

**Comment by chphilli** [comment]
Has this changed again in recent versions of Windows 10 by any chance? How do I go about finding the classname of alt-tab to check?

**Comment by chphilli** [comment]
Oh - of course right after I finally wrote that I found this: https://msdn.microsoft.com/en-us/library/windows/desktop/ms633574(v=vs.85).aspx#system . I added #32771 to the blacklist and now I can click on windows in alt-tab again.
