### ISSUE TITLE
"Scroll inactive Windows" breaks scrolling in Windows 10 applications

### ISSUE THREAD

**Issue by hoshsadiq** [stefansundin/altdrag#36]
The following can't be scrolled any more:
- Start menu
- Volume control

Other things that I can't remember, however, other applications work fine (Chrome, Spotify etc).

This feature should be removed completely for Windows 10 as this functionality comes by default.

**Comment by stefansundin** [comment]
When I first installed Win 10, I couldn't scroll the start menu either. Now it works for some reason. I don't think it's related to AltDrag, as I tried disabling it before, without effect. I suspect Microsoft pushed a fix for the bug.

I will probably remove the _Scroll inactive windows_ in a future release, after v1.1.

**Comment by SadBunny** [comment]
For anyone new to this issue (like me):

I just upgraded to W10 an hour ago. Pretty happy with it, MS seems to have done quite the job. At least from a user perspective - didn't go in deep yet. But I had the same problem. Problem is that W10 already has built-in "scroll inactive windows" functionality. Which is awesome! You can turn it on and off too (see "Mouse and touchpad" settings -> "Scroll inactive windows"). Suggestion: detect Windows 10 and default that AltDrag setting to off (or have an installation choice or something).

By the way, happy to see that AltDrag still functions fine in W10 - used AltDrag for a couple of weeks now and I can't imagine ever having been without it..

**Comment by patricf** [comment]
Disable "Scroll inactive windows" in AltDrag solved it for me.
You could make it scroll in Start, Settings etc. if you would hold down alt and scroll.
Didn't know "scroll inactive windows" was implemented in Windows 10 itself.
