### ISSUE TITLE
Scroll inactive windows causes two finger touchpad scroll to freeze input on windows 10

### ISSUE THREAD

**Issue by apatternjugglers** [stefansundin/altdrag#47]
I've just spent a couple of hours getting to the bottom of my issue, where by starting a two-finger touchpad scroll in Firefox, Chrome, Libreoffice and others will freeze all touchpad and touchscreen input for 3-20 seconds.

I think I've tracked it to AltDrag, and in particular the Scroll Inactive Windows setting
I have 100% reproducability of the result, and if I either disable AltDrag from the systray, or disable Scroll Inactive Windows, the problem disappears.

I'm happy to leave the setting turned off to fix, but a bugfix would be nice!
Please advise if there's any testing I could assist with.

**Comment by stefansundin** [comment]
On Windows 10 you should not need the _Scroll inactive windows_ feature since Microsoft built it in to Windows itself. I am considering to remove the feature (or automatically disable it on Win 10) in a future version.

**Comment by apatternjugglers** [comment]
Thanks for the quick reply.
I mainly wanted to report the very undesirable side-effect, which you may not have encountered.
I think automatically disabling the option in Win10 would be good, as it would avoid users having the issue in an otherwise excellent piece of software.

On a side note I know MS changed some scrolling behaviour in Win10, but there are still places I find it inconsistent, in particular I still need to activate side panels to scroll in some instances. 
AltDrag has been great for helping me tolerate Windows when needed.
