### ISSUE TITLE
Window snapping doesn't appear to be able to differentiate between workspaces

### ISSUE THREAD

**Issue by Zer0t3ch** [stefansundin/altdrag#53]
I.E: a window being moved on workspace 2 will snap to windows on workspace 1

**EDIT - "Task View" as Windows calls it

**Comment by stefansundin** [comment]
Hi. I was able to confirm the issue.

It appears I need to use the new `IVirtualDesktopManager` interface and use the function `IsWindowOnCurrentVirtualDesktop` to determine if the window is on the current desktop or not.

More info here:
- http://blogs.msdn.com/b/winsdk/archive/2015/09/10/virtual-desktop-switching-in-windows-10.aspx
- https://msdn.microsoft.com/en-us/library/windows/desktop/mt186442(v=vs.85).aspx

Thanks for reporting.

**Comment by Zer0t3ch** [comment]
Seems to be fixed in current builds.
