### ISSUE TITLE
AltDrag stops working after login on locked screen on Windows 7 running Synergy Server

### ISSUE THREAD

**Issue by paspil** [stefansundin/altdrag#58]
I'm running Windows 7 Professional 64 Bit with Synergy as server in version 1.7.6. AltDrag and Synergy working fine until i lock the screen. After login again AltDrag stops working after a few seconds. Deactivating and activating AltDrag does nothing.
Only when i stop the Synergy service, deactivate an activate AltDrag and start the Synergy service again, everthing works as expected.
I'm using only the left Alt key.

[altdrag.ini.txt](https://github.com/stefansundin/altdrag/files/197141/altdrag.ini.txt)
[synergy.sgc.txt](https://github.com/stefansundin/altdrag/files/197144/synergy.sgc.txt)

**Comment by trysten** [comment]
Same issue here on Windows 10 Pro 64bit. I've found it does continue to work on cmd.exe windows when Synergy is running, but no other windows seem to get hooked.

**Comment by paspil** [comment]
Switched to AltSnap and don't use Synergy anymore.
