### ISSUE TITLE
Aero Snap doesn't expand windows enough

### ISSUE THREAD

**Issue by saultyevil** [stefansundin/altdrag#62]
![2016-05-28_20-56-43](https://cloud.githubusercontent.com/assets/19627279/15629657/b8705612-2516-11e6-8252-6aa12e2fa9a1.png)

I'm using the mimic aero snap to snap windows into sides of the monitor, but the windows are not expanding to their full size. I've attached an image showing the difference. On the left is the normal aero snap and on the right is the snap from AltDrag; you should be able to see that it hasn't filled that half of the screen fully. My monitor is 3440x1440 and I applied the high DPI workaround just in case, but the issue still occurs.

**Comment by stefansundin** [comment]
This is a Windows 10 issue, there is no workaround at this moment. I think I have to use new APIs to account for new hidden borders.

Also discussed in https://github.com/stefansundin/altdrag/issues/38
