### ISSUE TITLE
Can't get "Identify window" to work on alt-tab in Windows 10

### ISSUE THREAD

**Issue by andrige** [stefansundin/altdrag#67]
Can't get the name of the window (since you are required to left click it instantly stows the window away), making it pretty much impossible to get the window name that way. Because of this I can't actually click on the alt-tab view to move to another program due to AltDrag.

I suggest maybe updating the blacklist to include Windows 10 alt-tab window name in the future.

**Comment by stefansundin** [comment]
The Alt+Tab window in Windows 10 should be blacklisted by default, but if you accidentally removed it, here it is: `*|MultitaskingViewFrame`

More details on the default blacklist items here: https://stefansundin.github.io/altdrag/doc/blacklist.html

**Comment by andrige** [comment]
Okay! Sorry about that, didn't really consider looking in the docs because I was sure I had never touched the blacklist, but guess I must have had at some point. 

Thanks!
