### ISSUE TITLE
[suggestion]make transparency change step less

### ISSUE THREAD

**Issue by zldrq** [stefansundin/altdrag#70]
hi!

When scroll wheel is used to change transparency, it changes with the step of ~20%. 
It is very big number and pretty much not usable for me, since i usually want to change transparency in upper 25%, 75-100% that is.

Can you please add setting to adjust the step or just make the step less, like 5%.

I understand that it may depend on my mousewheel settings or mouse, but they are default, 3 lines per wheel "tick". That said, having the option to adjust should be better, since ppl use different scroll wheel settings.

**Comment by stefansundin** [comment]
Try holding down the shift key to use smaller steps.

**Comment by zldrq** [comment]
@stefansundin wow, thanks!
Strange, that I didn't check it myself.
Sorry for polluting issues section.

**Comment by stefansundin** [comment]
No problems. :)

Read this page for more tricks: https://stefansundin.github.io/altdrag/doc/usage.html
