### ISSUE TITLE
Feature Request: Hide tray icon without autostart or introduce an AltDrag Windows Service

### ISSUE THREAD

**Issue by ChaosMarc** [stefansundin/altdrag#80]
I bypass the UAC problem of an elevated autostart by disabling it in altdrag and start the tool with an elevated windows task (see e. g. https://superuser.com/questions/770420/schedule-a-task-with-admin-privileges-without-a-user-prompt-in-windows-7).
My problem is that I can't hide the tray icon without enabling the autostart option in altdrag itself. Please remove the dependency of "Hide Tray Icon" to "Start AltDrag with Windows"

As an alternative you could implement an elevated windows service that runs in the background and starts AltDrag if the user chooses to.

PS: I always display all tray icons as I dislike not seeing all active icons, so hiding the tray icon via windows sadly is not an option.

PPS: I only now stumbled upon #14. Please don't remove the option to hide the icon! I think it is very substantial to have the ability to hide icons of apps that don't need to be configured regularly  (or like AltDrag, never after the initial configuration)

**Comment by stefansundin** [comment]
Hi @ChaosMarc,

I think you can pass arguments in the task scheduler. Can you try passing in `-hide`?

Let me know if it works.

**Comment by ChaosMarc** [comment]
Hey @stefansundin,

that worked flawlessly :) Thank you very much!
