### ISSUE TITLE
alt-drag completely breaks with 4k resolution and other display settings

### ISSUE THREAD

**Issue by chrisdtaylor** [stefansundin/altdrag#88]
I've been loving alt-drag for a while now.  I recently got a 4k monitor and found that alt-drag goes nuts when doing alt-drag things on windows in the 4k monitor.  For example, it doesn't "grab" the window the cursor is on but rather some other window.  This makes the alt-left-click + drag action useless.  Similar behavior happens when trying to resize using alt-right-click + drag.

Along the way I've also noticed that alt-drag gets thrown off if you have a non-100% display scale factor (something you tend to do with a 4k monitor).  I tested that without the 4k monitor connected and found that alt-drag breaks down in similar ways.

I'd love to hear if a fix is possible or if I should look elsewhere for a similar utility.  One promising option out there (not free) is this one: http://mizage.com/windivvy/.  I'm not yet sure if it does everything alt-drag (used to) do for me, but I'm looking.

I'm also content to hear, "yeah, alt-drag dev is dead and you should just look elsewhere" if that's where things are :).

**Comment by stefansundin** [comment]
AltDrag is not dead, but on life support, because I don't have the time to work on it. It's just a hobby. I think your problems may be fixed if you follow these instructions: https://github.com/stefansundin/altdrag/issues/7#issuecomment-50701359

**Comment by chrisdtaylor** [comment]
@stefansundin, thanks for the reply!  I do appreciate that this is a hobby and that hobbies get low priority.

I have attempted to follow the linked comment you gave, but when I open up AltDrag properties window, I don't have a Compatibility tab.  Here's what mine looks like:

![image](https://user-images.githubusercontent.com/13205276/33353104-ee99081a-d460-11e7-9438-655c1be20ac3.png)

And to confirm the version I have (freshly installed, I might add):

![image](https://user-images.githubusercontent.com/13205276/33353116-01d46456-d461-11e7-8355-e65e0164dc1c.png)

Any idea what I might be missing? Is it possible my corporate IT has somehow limited something here?

**Comment by chrisdtaylor** [comment]
It finally clicked.  I need to find the .exe (as the comment clearly states), not right-click the tray icon.  Will try that.  Thanks!
