### ISSUE TITLE
Add license file please

### ISSUE THREAD

**Issue by L1Q** [stefansundin/altdrag#89]
Your [website](https://stefansundin.github.io/) implies that all your work is licensed under GNU GPL v3. Futhermore the altdrag page on the website states the same.

However I believe you break the terms of the very license you state using by not providing the license file with your source and/or binary distributions. And those short notices in source code are not enough without links or actual license file.

Therefore I [ask you nicely](https://choosealicense.com/no-permission/) to add a license.md file to this repository.

**Comment by stefansundin** [comment]
File added.
