### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by dnknn** [stefansundin/altdrag#93]
sorry

**Comment by dnknn** [comment]
In addition, I have not changed the DPI scaling behavior,
I have also tried the following solutions and still cannot solve the `Winkey `button problem.

For example, run AltDrag in compatibility mode, run as administrator...
![123](https://user-images.githubusercontent.com/10995302/39153119-cb345138-477c-11e8-8de8-ae8ef9ebafee.png)

However, it still failed to solve the problem of `Winkey` button.
I do not know the reason for this problem.

**Comment by vadviktor** [comment]
Just FYI, it is a special case for you as I am still using Win 10 (pro) and using the win key and works. Using it on a laptop and works both on the laptop's keyboard and on an external keyboard. I made no special settings to AltDrag.
